name: 'Python Lockfile Update'
description: "This action uses pip-tools to update a project's lockfiles via a Pull Request."

branding:
  icon: 'arrow-up-circle'
  color: 'purple'

inputs:

  deploy_key:
    description: "A deploy key with write access to the repository. This is required if you wish the PR to trigger workflows, as commits made with the Github Token will not. It is recommended to use a repository locked deploy key."
    required: false

  pr_body_text:
    description: "the Pull Request comment for Pull Requests opened by this action."
    required: true
    default: "This Automated PR updates the requirements.txt files to the latest versions. As this is automated it should be reviewed for errors before merging."

  pr_title:
    description: "The Pull Request title for pull requests opened by this action."
    required: true
    default: "Automated Requirements File Updates"

  github_username:
    description: "The username to use for commits from this action."
    required: false
    default: ${{ github.actor }}

  branch_prefix:
    description: "A prefix used for generating branch names for the Pull Requests generated by this action."
    required: true
    default: "pip-update"

  pip_extras:
    description: "A list, separated by spaces, of `extra` packages to install."
    required: false
    default: ""

  commit_message:
    description: "Updating versions for python lockfiles."
    required: true
    default: "Automated Requirements File Updates"

  base_branch:
    description: "The branch to make Pull Requests against."
    required: true
    default: "main"

runs:
  using: "composite"
  steps:

    - name: Install pip-tools
      run: python -m pip install pip-tools
      shell: bash

    - name: Update and Push
      run: bash ${{ github.action_path }}/scripts/update.sh
      shell: bash
      env:
        PR_BODY_TEXT: ${{ inputs.pr_body_text }}
        PR_TITLE: ${{ inputs.pr_title }}
        DEPLOY_KEY: ${{ inputs.deploy_key }}
        BRANCH_PREFIX: ${{ inputs.branch_prefix }}
        PIP_EXTRAS: ${{ inputs.pip_extras }}
        COMMIT_MESSAGE: ${{ inputs.commit_message }}
        BASE_BRANCH: ${{ inputs.base_branch }}
        GITHUB_USERNAME: ${{ inputs.github_username }}
