name: Update Dependencies and Push to Github

on:
  push:
    paths:
      # On push if the example file has changed.
      - '.github/workflows/example-key.yml'
  schedule:
      # Every Monday at 1PM UTC (9AM EST)
    - cron: "0 13 * * 1"


jobs:
  push-updates-with-key:
    runs-on: ubuntu-latest

    # Permission is still needed by the token to open the PR.
    permissions:
      pull-requests: write

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: "Update Lockfiles and Open PR"
        uses: aptible/action-python-lockfile-update
        with:
          # Each "extra" is space separated.
          # This actions will end up with three files
          # * requirements.txt
          # * requirements-testing.txt
          # * requirements-sqs.txt
          pip_extras: "testing sqs"

          # This key will bypass workflow limitations to ensure tests are run.
          deploy_key: SECRETS.deploy_key
